### ISSUE TITLE
"AssertionError: has_mat() at line 461 of c:\buildslave\sdk-windows-i386\build\built1.10\include\transformState.I"

### ISSUE THREAD

**Issue by zurgeg** [el-dee/panda3d-openvr#12]
**Setup**
Headset: HTC Vive
Controllers: Valve Index Knuckles
SteamVR Version: 1.15.16
**Issue**
Upon running my game, it seems to work fine, until the SteamVR Menu (revealed by pressing the System button [Wands/Knuckles] or the menu/hamburger button [Touch 1 and 2]) is opened, and the game crashes with:
```
Traceback (most recent call last):
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\p3dopenvr\p3dopenvr.py", line 312, in left_cb
    cbdata.upcall()
AssertionError: has_mat() at line 461 of c:\buildslave\sdk-windows-i386\build\built1.10\include\transformState.I
Traceback (most recent call last):
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\p3dopenvr\p3dopenvr.py", line 317, in right_cb
    cbdata.upcall()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\p3dopenvr\p3dopenvr.py", line 312, in left_cb
    cbdata.upcall()
AssertionError: has_mat() at line 461 of c:\buildslave\sdk-windows-i386\build\built1.10\include\transformState.I
Traceback (most recent call last):
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\showbase\ShowBase.py", line 2020, in __igLoop
    self.graphicsEngine.renderFrame()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\p3dopenvr\p3dopenvr.py", line 317, in right_cb
    cbdata.upcall()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\p3dopenvr\p3dopenvr.py", line 312, in left_cb
    cbdata.upcall()
AssertionError: has_mat() at line 461 of c:\buildslave\sdk-windows-i386\build\built1.10\include\transformState.I
Traceback (most recent call last):
  File "C:\Users\zurgE\OneDrive\Documents\3D Python programs\firehawk_vr2.py", line 456, in <module>
    App().run()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\showbase\ShowBase.py", line 3152, in run
    self.taskMgr.run()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\task\Task.py", line 537, in run
    self.step()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\task\Task.py", line 491, in step
    self.mgr.poll()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\showbase\ShowBase.py", line 2020, in __igLoop
    self.graphicsEngine.renderFrame()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\p3dopenvr\p3dopenvr.py", line 317, in right_cb
    cbdata.upcall()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\p3dopenvr\p3dopenvr.py", line 312, in left_cb
    cbdata.upcall()
AssertionError: has_mat() at line 461 of c:\buildslave\sdk-windows-i386\build\built1.10\include\transformState.I
```
In theory, this could be caught and removed(?) once the latest release with error handling is out (by `pass`ing on the error, which would most likely cause a freeze/further crashing sadly). It appears to by caused by the game not pausing when the universal menu is opened. 

Interestingly enough, when this happens, the game doesn't actually run again until you reboot SteamVR, which would not be great in a production environment!

**Comment by zurgeg** [comment]
Update:
With the following snippet, added to `p3dopenvr.py`:
```python
    def on_compositor_error(e):
        raise e
    def left_cb(self, cbdata):
        try:
            cbdata.upcall()
            if not self.submit_together:
                self.submit_texture(openvr.Eye_Left, self.left_texture)
        except Exception as e:
            self.on_compositor_error(e)

    def right_cb(self, cbdata):
        try:
            cbdata.upcall()
            if not self.submit_together:
                self.submit_texture(openvr.Eye_Left, self.left_texture)
                self.submit_texture(openvr.Eye_Right, self.right_texture)
        except Exception as e:
            self.on_compositor_error(e)
```
and this one added to my code in the P3DOpenVR class derivative:
```python
    def on_compositor_error(self,e):
        if type(e) != AssertionError:
            raise e
```
The game continues to run, however, doesn't not submit any frames to SteamVR.
@el-dee Should this be the default compositor error handling once I get a PR up and running for compositor error handling?

**Comment by el-dee** [comment]
I tested on my setup and opening the System overlay does not cause any problem, the app is actually still running in the background.

The assertion is probably due to an invalid matrix retrieved from one of the pose and used in the scenegraph. I'm a bit reluctant to add such wide exception catch (unless there is no other way).

Instead I would implement detection of the system menu event and add a callback / method in p3dopenvr so the application can freeze while the menu is open.

**Comment by el-dee** [comment]
If an action is not valid, they now return None. Also, p3dopenvr has a property `has_focus` that can be used to check if the app has the focus on the input devices.
